# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "af195b240516fde12071c40091581d24"
name = "WaNotify"
handle = "wanotify-app-2025"
application_url = "https://saving-drake-eternal.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled" ]
  uri = "/webhooks/orders/fulfilled"

  [[webhooks.subscriptions]]
  topics = [ "carts/create" ]
  uri = "/webhooks/carts/create"

  [[webhooks.subscriptions]]
  topics = [ "carts/update" ]
  uri = "/webhooks/carts/update"

  [[webhooks.subscriptions]]
  topics = [ "customers/create" ]
  uri = "/webhooks/customers/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,write_products,read_customers"

[auth]
redirect_urls = ["https://saving-drake-eternal.ngrok-free.app/auth/callback", "https://saving-drake-eternal.ngrok-free.app/auth/shopify/callback", "https://saving-drake-eternal.ngrok-free.app/api/auth/callback"]

[pos]
embedded = false
